# Hostapp composition overlay for raspberrypi4-64.
# Defines the hostapp and extension services for the composition build pipeline.
# In production, the hostapp service will move to a base composition in meta-balena
# and this file will only declare device-specific extensions.
version: '2.4'
services:

  hostapp:
    image: __BUILD_OUTPUT__
    x-build:
    labels:
      io.balena.image.store: 'root'
      io.balena.image.class: 'hostapp'
      io.balena.update.requires-reboot: '1'
      io.balena.private.hostapp.board-rev: '${DEVICE_REPO_REV}'

  kernel-modules:
    image: __BUILD_OUTPUT__
    x-build:
      recipe: balena-kernel-modules-block
      layers:
        - layers/meta-kernel-modules-block
      sample_conf: layers/meta-kernel-modules-block/conf/samples
    profiles:
      - kernel-modules
    labels:
      io.balena.image.store: 'data'
      io.balena.image.class: 'overlay'
      io.balena.update.requires-reboot: '1'
