# yaml-language-server: $schema=https://raw.githubusercontent.com/compose-spec/compose-spec/master/schema/compose-spec.json
version: '2.4'
services:

  kernel-modules:
    image: __BUILD_OUTPUT__
    profiles:
      - kernel-modules
    x-build:
      recipe: balena-kernel-block
      build_args:
        - "-t"
        - "layers/meta-kernel-block/conf/samples"

  debug:
    image: __BUILD_OUTPUT__
    profiles:
      - debug
    x-build:
      recipe: balena-debug-block
      build_args:
        - "-t"
        - "layers/meta-debug/conf/samples"
