# yaml-language-server: $schema=https://raw.githubusercontent.com/balena-os/balena-yocto-scripts/refs/heads/kyle/hostapp-extensions-workflow/schemas/hostapp-composition.json
version: '2.4'
services:

  kernel-modules:
    image: __BUILD_OUTPUT__
    x-build:
      recipe: balena-kernel-modules-block
      build_args:
        - "-t"
        - "layers/meta-kernel-modules-block/conf/samples"
