#!/bin/sh
# Copyright 2023 Balena Ltd.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#    http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

# vi: ft=sh

# shellcheck disable=SC1091
[ -f "/usr/libexec/os-helpers-logging" ] && . /usr/libexec/os-helpers-logging

BALENA_NONENCRYPTED_BOOT_PARTITION_FILES="\
    boot.img \
    boot.scr \
    boot.sig \
    config.txt \
    bcm2711-rpi-400.dtb \
    bcm2711-rpi-4-b.dtb \
    bcm2711-rpi-cm4.dtb \
    @@BALENA_IMAGE_FLAG_FILE@@ \
    extra_uEnv.txt \
    @@KERNEL_IMAGETYPE@@ \
    bootenv \
"

doSkip() {
	_file="$1"
	for b in $BALENA_NONENCRYPTED_BOOT_PARTITION_FILES; do
		# See if file is in the non-encrypted boot partition file list
		if [ "$b" = "$(basename "$_file")" ]; then
			# If so, skip (return 0) if running the 1-bootfiles script that copies files
			# to the non-encrypted /mnt/boot partition
			# If running a different script, return 1 not to skip it
			test "$(basename $0)" = "1-bootfiles"
			return
		fi
	done
	# The file is in the encrypted boot partition file list, so do not skip (return 1) if running
	# the 1-bootfiles script that copies files to the encrypted /mnt/boot partition
	# If running a different script, return 0 to skip it
	test "$(basename "$0")" != "1-bootfiles"
}
