#!/bin/sh

#
# This hook updates raspberrypi4 vl805 firmware
#

set -o errexit

CURR_IMG=vl805fw-current.bin.tmp
CURR_IMG_PATH=/dev/shm
NEW_IMG=vl805-latest-stable.bin
NEW_IMG_PATH=/mnt/boot

/usr/sbin/vl805 -r ${CURR_IMG_PATH}/${CURR_IMG} || true

# Don't fail if firmware cannot be read
# for some reason
if [ ! -f ${CURR_IMG_PATH}/${CURR_IMG} ]; then
    echo "[WARN] Could not read current vl805 firmware!"
    exit 0
fi;

curr_vl805fw_md5sum=$(md5sum ${CURR_IMG_PATH}/${CURR_IMG} | awk '{print $1}')
new_vl805fw_md5sum=$(md5sum ${NEW_IMG_PATH}/${NEW_IMG} | awk '{print $1}')

if [ $curr_vl805fw_md5sum = $new_vl805fw_md5sum ]; then
    echo "[INFO] vl805 firmware update is not necessary"
else
    echo "[INFO] Performing vl805 firmware update..."
    /usr/sbin/vl805 -w ${NEW_IMG_PATH}/${NEW_IMG} || true
fi

rm ${CURR_IMG_PATH}/$CURR_IMG
