#!/bin/sh

#
# Script which configures the cleans up redundant files in the boot partition
#

set -o errexit

. /usr/sbin/resin-vars

DURING_UPDATE=${DURING_UPDATE:-0}

if [ "$DURING_UPDATE" = "1" ]; then
	if  grep -q "ext4load" "$RESIN_BOOT_MOUNTPOINT/boot.scr" ; then
		if [ -e "$RESIN_BOOT_MOUNTPOINT/zImage" ]; then
			# Testing the destination sysroot kernel is tricky. Lets check current root
			# instead as all future roots will have the kernel in root partition in /boot
			# This leaves the kernel lying around in boot partition until the next HUP
			if [ -e "/boot/zImage" ]; then
				printf "[INFO] u-boot boot.scr now reads kernel from root partitions but found zImage in boot \n"
				printf "[INFO] removing $RESIN_BOOT_MOUNTPOINT/zImage \n"
				rm -f "$RESIN_BOOT_MOUNTPOINT/zImage" || true
				sync -f "$RESIN_BOOT_MOUNTPOINT"
			fi
		fi
	fi
fi
