#!/bin/sh

#
# Script which configures the cmdline.txt for RaspberryPi to use an updated
# root kernel argument
#

set -o errexit

DURING_UPDATE=${DURING_UPDATE:-0}

if [ "$DURING_UPDATE" = "1" ]; then
       SYSROOT="/mnt/sysroot/inactive"
else
       SYSROOT="/mnt/sysroot/active"
fi

new_part=$(findmnt --noheadings --canonicalize --output SOURCE $SYSROOT)
new_part_label=$(blkid "$new_part" | awk '{print $2}')

printf "[INFO] Switching RaspberryPi bootloader root partition index to %s..." "$new_part_label..."
cp /mnt/boot/cmdline.txt /mnt/boot/cmdline.txt.new
sed -i "s/root=[^ ]* /"root=$new_part_label" /mnt/boot/cmdline.txt.new
sync -f /mnt/boot
mv /mnt/boot/cmdline.txt.new /mnt/boot/cmdline.txt
sync -f /mnt/boot
printf " done.\n"
