name: Raspberry Pi 3

on:
  # https://docs.github.com/en/actions/writing-workflows/workflow-syntax-for-github-actions#onpushbranchestagsbranches-ignoretags-ignore
  # https://docs.github.com/en/actions/writing-workflows/workflow-syntax-for-github-actions#filter-pattern-cheat-sheet
  pull_request:
    branches:
      - main
      - master
      # ESR branches glob pattern
      - v20[0-9][0-9].[0-1]?[1470].[0-9]+
  pull_request_target:
    branches:
      - main
      - master
      # ESR branches glob pattern
      - v20[0-9][0-9].[0-1]?[1470].[0-9]+
  push:
    tags:
      # Semver tags glob pattern (includes ESR in format v20YY.MM.PATCH)
      - v[0-9]+.[0-9]+.[0-9]+\+?r?e?v?*
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:
    inputs:
      force-finalize:
        description: Force finalize of the build (implicitly enables hostapp and S3 deployments)
        required: false
        type: boolean
        default: false
      deploy-environment:
        description: Environment to use for build and deploy
        required: false
        type: string
        default: balena-staging.com

jobs:
  yocto:
    name: Yocto
    uses: balena-os/balena-yocto-scripts/.github/workflows/yocto-build-deploy.yml@kyle/check-tests ## latest from https://github.com/balena-os/balena-yocto-scripts/pull/386/commits
    # Prevent duplicate workflow executions for pull_request (PR) and pull_request_target (PRT) events.
    # Both PR and PRT will be triggered for the same pull request, whether it is internal or from a fork.
    # This condition will prevent the workflow from running twice for the same pull request while
    # still allowing it to run for all other event types.
    if: (github.event.pull_request.head.repo.full_name == github.repository) == (github.event_name == 'pull_request')
    secrets: inherit
    with:
      machine: raspberrypi3
      # Needed for testing - defaults to production
      # Default to balena-staging.com for workflow dispatch, but balena-cloud.com for other events
      deploy-environment: balena-staging.com
      test_matrix: >
        {
          "test_suite": ["os"],
          "environment": ["bm.balena-dev.com"],
          "runs_on": [["ubuntu-latest"]]
        }
      # Allow manual workflow runs to force finalize without checking previous test runs
      force-finalize: ${{ inputs.force-finalize || false }}
